module.exports = {
  CONNECTION_REQUEST: 'CONNECTION_REQUEST',
  CONNECTION_SUCCESS: 'CONNECTION_SUCCESS',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  CONNECTION_LOST: 'CONNECTION_LOST',
  GAME_START_REQUEST: 'GAME_START_REQUEST',
  GAME_END_REQUEST: 'GAME_END_REQUEST',
  GAME_ABORT_REQUEST: 'GAME_ABORT_REQUEST'
};
